---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: document
  path: apresentacao.html
  label: Apresentação
- type: document
  path: sobre.html
  label: Sobre Nós
- type: document
  path: amazonia.html
  label: Amazónia
- type: document
  path: guatemala.html
  label: Guatemala
- type: document
  path: contacto.html
  label: Contacto
- type: document
  path: termos.html
  label: Termos e Condições
- type: document
  path: privacidade.html
  label: Privacidade
upload_dir: assets/img
public_path: assets/img
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
